/**
 * The branch model, in one place.
 *
 * These rules already exist in `apps/saas`, but only as string literals spread
 * across `src/lib/projects.ts:54,66`, `src/lib/demo-workflow.ts` (a dozen
 * sites), `app/api/projects/[projectId]/edits/route.ts:25` and the `main` guard
 * in `app/api/projects/[projectId]/checkpoint/route.ts:32-34`. With two more
 * apps about to encode the same rules, that drift becomes a correctness
 * problem, so this module is the single definition all new code imports.
 *
 *   main    production; releases are tagged here; never a direct edit target
 *   test    integration; the base for every tmp branch
 *   tmp-*   active edits; merges to `test`, NEVER straight to `main`
 */

export const PROD_BRANCH = "main";
export const INTEGRATION_BRANCH = "test";
export const TMP_PREFIX = "tmp-";

/**
 * Lowercase, collapse to `-`, cap length. Deliberately identical to
 * `apps/saas/src/lib/projects.ts:148` so branch names generated by the SaaS and
 * by the new apps cannot diverge for the same input.
 */
export function slugify(input: string): string {
  const s = input
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .slice(0, 60);
  return s || "untitled";
}

/** `tmp-<user>-<edit>` — matches the SaaS naming at edits/route.ts:25. */
export function tmpBranchName(userSlug: string, editName: string): string {
  return `${TMP_PREFIX}${slugify(userSlug)}-${slugify(editName)}`;
}

export function isTmpBranch(branch: string): boolean {
  return branch.startsWith(TMP_PREFIX) && branch.length > TMP_PREFIX.length;
}

export function isProdBranch(branch: string): boolean {
  return branch === PROD_BRANCH;
}

export function isIntegrationBranch(branch: string): boolean {
  return branch === INTEGRATION_BRANCH;
}

/** Branches the editor may write to. `main` is never one of them. */
export function isWritableBranch(branch: string): boolean {
  return isTmpBranch(branch) || isIntegrationBranch(branch);
}

export class MergeTargetError extends Error {
  constructor(message: string) {
    super(message);
    this.name = "MergeTargetError";
  }
}

/**
 * Reject an illegal merge before it can be requested.
 *
 * Enforcing this at the client layer rather than in each app means neither the
 * hub nor the extension can even express `tmp-* -> main`, which is the mistake
 * the branch model exists to prevent: it would put unreviewed work straight
 * into production and into a public release URL.
 */
export function assertMergeTarget(head: string, base: string): void {
  if (head === base) {
    throw new MergeTargetError(`Cannot merge ${head} into itself.`);
  }
  if (isTmpBranch(head) && isProdBranch(base)) {
    throw new MergeTargetError(
      `${head} cannot merge directly into ${PROD_BRANCH}. ` +
        `Edit branches merge into ${INTEGRATION_BRANCH} first, and only released ` +
        `versions are promoted to ${PROD_BRANCH}.`,
    );
  }
  if (isTmpBranch(head) && !isIntegrationBranch(base)) {
    throw new MergeTargetError(`${head} may only merge into ${INTEGRATION_BRANCH}, not ${base}.`);
  }
  if (isProdBranch(head)) {
    throw new MergeTargetError(
      `${PROD_BRANCH} is the production branch and is never a merge source.`,
    );
  }
}

/** Checkpoints are commits; `main` never receives one directly (see checkpoint/route.ts:32-34). */
export function assertCheckpointTarget(branch: string): void {
  if (isProdBranch(branch)) {
    throw new MergeTargetError(`Checkpoints are not allowed directly on ${PROD_BRANCH}.`);
  }
}
